name: MacOS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "**.rs", "**.toml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
     
    ######  - name: Install Homebrew
     ######   run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ######  - name: Update Homebrew
      ######  run: brew update
     ###### - name: Install dependencies
      ######  run: 
        ###### brew install libxcomposite pkg-config fontconfig
         #brew install --cask cmake
   # pkg-config cmake libxcb-composite0-dev libfontconfig1-dev

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions/setup-rust@v2

      #- name: Setup Xcode
       # uses: maxim-lobanov/setup-xcode@v1
        #with:
         # xcode-version: latest
      - name: build
        run: cargo build --release
      - name: Install create-dmg
        run: npm install create-dmg -g
      - name: Create DMG 
        run: creat-dmg ./target/release/aida64-keys-gui ./output/Aida64-Keys.dmg --volname "Aida64 Keys" --icon "./path/to/icon.icns"
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v2
        with:
          name: aida64-keys-dmg
          path: output/Aida64-Keys.dmg

 


    
