name: MacOS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "**.rs", "**.toml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --verbose

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: Create DMG
        run: create-dmg ./target/debug/aida64-keys-gui ./output/Aida64-Keys.dmg --volname "Aida64 Keys" --icon "./path/to/icon.icns"

      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: Aida64-Keys.dmg
          path: ./output/Aida64-Keys.dmg

 


    
