name: MacOS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "**.rs", "**.toml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      ######- name: Setup Xcode
       ###### uses: maxim-lobanov/setup-xcode@v1
      ######  with:
        ######  xcode-version: latest
    ######  - name: Install Homebrew
     ######   run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ######  - name: Update Homebrew
      ######  run: brew update
     ###### - name: Install dependencies
      ######  run: 
        ###### brew install libxcomposite pkg-config fontconfig
         #brew install --cask cmake
   # pkg-config cmake libxcb-composite0-dev libfontconfig1-dev

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install create-dmg
        run: npm install create-dmg -g

      - name: Build application
        run: cargo build --release

      - name: Create DMG file
        run: create-dmg ./target/debug ./output --volname "MyApp" --icon "icon.icns"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp.dmg
          path: ./output/MyApp.dmg

     ###### - name: Build
       ###### run: cargo build --verbose

      #- name: Add MacOS-dmg target
        #run: rustup target add x86_64-apple-darwin

      #- name: Build MacOS app-dmg
        #run: cargo build --target x86_64-apple-darwin

    ######  - name: Upload artifact
      ######  uses: actions/upload-artifact@master
     ######   with:
      ######    name: MacOS_DMG
      ######    path: ./
    
