name: MacOS

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
  
      - name: Build
        run: cargo build --verbose
      - name: Add x86_64-apple-darwin
        run: rustup target add x86_64-apple-darwin
      - name: Make cargo
        run: cargo build --target x86_64-apple-darwin
     # - name: Upload 
      #  uses: actions/upload-artifact@master
       # with:
        #  name: For_Macos
         # path: ./
   #   - name: Create Output Directory
    #    run: mkdir -p ${{ github.workspace }}/output
     #   working-directory: ${{ github.workspace }}
      
      - name: Install create-dmg
        run: brew install create-dmg -g 
      - name: Set permissions folder
        run: chmod -R 777 ./target
        
      - name: Check Target Folder
        run: |
         ls -al ./target/x86_64-apple-darwin/
         echo "Target Folder Exists"
        
      - name: Create DMG
        run: create-dmg "${{ github.workspace }}/target/x86_64-apple-darwin/debug/aida64-keys-gui" "${{ github.workspace }}/target/x86_64-apple-darwin/Aida64-Keys.dmg" --volname "Aida64 Keys" --icon "${{ github.workspace }}/.github/workflows/icon.icns"
        working-directory: ${{ github.workspace }}
      
      - name: Check Output File
        run: |
         ls -al ./target/Aida64-Keys.dmg
         echo "Output File Exists"
        
      
      - name: Upload DMG
        uses: actions/upload-artifact@master
        with:
          name: Aida64Keys.dmg
          path: ./output/Aida64-Keys.dmg
