name: MacOS

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "**.rs", "**.toml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest
    steps:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: latest
     - run: brew install pkg-config cmake build-essential libxcb-composite0-dev libfontconfig1-dev    
     - uses: actions/checkout@v3
     - name: Build
       run: cargo build --verbose
     - name: add MacOS-dmg
       run: rustup target add MacOS-dmg
     - name: make MacOS-app-dmg
       run: cargo build --target MacOS-dmg
      
     - name : Upload artifact
       uses: actions/upload-artifact@master
       with:
         name: MacOS_DMG
         path: ./target  
    
