name: Ubuntu/Windows/MacOS

on:
  #workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "**.rs", "**.toml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  First_job:
    name: Linux
    runs-on: ubuntu-latest
    #runs-on: ${{ matrix.os }}
    #strategy:
      #matrix:
        #os: [ubuntu-latest]
       # os: [ubuntu-latest, macos-latest ]
    steps:
    - run: sudo apt-get install pkg-config cmake build-essential libxcb-composite0-dev libfontconfig1-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
       #run: cargo test --workspace --exclude aida64-keys-gui --verbose
    #- name : Upload artifact
     # uses: actions/upload-artifact@master
    #  with:
     #   name: Linux_File
      #  path: ./target/debug/
      
  Second_job:
    name: Windows
    runs-on: windows-latest
    
    steps:
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
     # run: cargo test --workspace --exclude aida64-keys-gui --verbose
    - name: add x86_64-pc-windows-gnu
      run: rustup target add x86_64-pc-windows-gnu
    - name: make win-gui
      run: cargo build --target x86_64-pc-windows-gnu
    #- name : Upload artifact
    #  uses: actions/upload-artifact@master
     # with:
      #  name: win_64-keysGUI
      #  path: ./target/x86_64-pc-windows-gnu/debug/aida64-keys-gui.exe
